# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets
from PySide2.QtGui import QPixmap, QIcon, QColor
from PySide2.QtWidgets import QWidget


class Ui_Form(QWidget):
    def __init__(self):
        super(Ui_Form, self).__init__()
        self.setupUi(self)
        self.retranslateUi(self)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1139, 833)
        Form.setWindowIcon(QIcon('./data/windows.png'))
        palette1 = QtGui.QPalette()
        palette1.setColor(Form.backgroundRole(), QColor(135, 206, 250))  # 背景颜色
        Form.setPalette(palette1)
        Form.setAutoFillBackground(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(8, 8))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.read_video = QtWidgets.QPushButton(Form)
        self.read_video.setMinimumSize(QtCore.QSize(12, 13))
        self.read_video.setObjectName("read_video")
        self.read_video.setStyleSheet(
            '''QPushButton{background:#FFFFFF;border-radius:5px;}QPushButton:hover{background:yellow;}''')
        self.gridLayout.addWidget(self.read_video, 1, 0, 1, 1)
        self.show_video = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.show_video.sizePolicy().hasHeightForWidth())
        self.show_video.setSizePolicy(sizePolicy)
        self.show_video.setMinimumSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.show_video.setFont(font)
        self.show_video.setFrameShape(QtWidgets.QFrame.Box)
        self.show_video.setAlignment(QtCore.Qt.AlignCenter)
        self.show_video.setObjectName("show_video")
        # pix = QPixmap('/data/windows.png')
        # self.show_video.setPixmap(pix)
        # self.show_video.setScaledContents(True)
        self.gridLayout.addWidget(self.show_video, 3, 2, 4, 1)
        self.show_message = QtWidgets.QTextBrowser(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_message.sizePolicy().hasHeightForWidth())
        self.show_message.setSizePolicy(sizePolicy)
        self.show_message.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.show_message.setObjectName("show_message")
        self.gridLayout.addWidget(self.show_message, 3, 0, 2, 1)
        self.label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.show_message2 = QtWidgets.QTextBrowser(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_message2.sizePolicy().hasHeightForWidth())
        self.show_message2.setSizePolicy(sizePolicy)
        self.show_message2.setObjectName("show_message2")
        self.gridLayout.addWidget(self.show_message2, 5, 0, 2, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "交通场景智能应用"))
        self.read_video.setText(_translate("Form", "读入视频"))
        self.show_video.setText(_translate("Form", "展示检测结果"))
        self.label.setText(_translate("Form", "交通场景智能应用"))
